for(let i=1;i<100;i++){
    let nr=1;
    if(i%17==0){
        if(i%13==0){
            process.stdout.write("Fezz");
            nr=0;
        }
        if(i%11==0){
            process.stdout.write("Bong");
            nr=0;
        }
        if(i%7==0){
            process.stdout.write("Bang");
            nr=0;
        }
        if(i%5==0){
            process.stdout.write("Buzz");
            nr=0;
        }
        if(i%3==0){
            process.stdout.write("Fizz");
            nr=0;
        }
    }
    else{
        if(i%3==0){
            process.stdout.write("Fizz");
            nr=0;
        }
        if(i%5==0){
            process.stdout.write("Buzz");
            nr=0;
        }
        if(i%7==0){
            process.stdout.write("Bang");
            nr=0;
        }
        if(i%11==0){
            process.stdout.write("Bong");
            nr=0;
        }
        if(i%13==0){
            process.stdout.write("Fezz");
            nr=0;
        }
    }
    if(nr==1){
        process.stdout.write(i.toString());
    }
    console.log();
}